// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitCatAlexiskh.Data;

#nullable disable

namespace RecruitCatAlexiskh.Migrations
{
    [DbContext(typeof(RecruitCatAlexiskhContext))]
    [Migration("20250915010530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CandidateJobTitle", b =>
                {
                    b.Property<int>("CandidatesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobTitlesID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidatesID", "JobTitlesID");

                    b.HasIndex("JobTitlesID");

                    b.ToTable("CandidateJobTitle");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.Candidate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.Industry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Industry");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.JobTitle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndustryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("IndustryID");

                    b.ToTable("JobTitle");
                });

            modelBuilder.Entity("CandidateJobTitle", b =>
                {
                    b.HasOne("RecruitCatAlexiskh.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitCatAlexiskh.Models.JobTitle", null)
                        .WithMany()
                        .HasForeignKey("JobTitlesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.JobTitle", b =>
                {
                    b.HasOne("RecruitCatAlexiskh.Models.Company", null)
                        .WithMany("JobTitles")
                        .HasForeignKey("CompanyID");

                    b.HasOne("RecruitCatAlexiskh.Models.Industry", null)
                        .WithMany("JobTitles")
                        .HasForeignKey("IndustryID");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.Company", b =>
                {
                    b.Navigation("JobTitles");
                });

            modelBuilder.Entity("RecruitCatAlexiskh.Models.Industry", b =>
                {
                    b.Navigation("JobTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
